trigger:
  branches:
    include:
      - master  # Adjust as per your branch structure

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'

stages:
  - stage: Build_and_Test
    jobs:
      - job: Build
        steps:
          
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean install'
          
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test -P smoke -Dsurefire.suiteXmlFiles=testng.xml'

      - job: Publish
        dependsOn: Build
        steps:
          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/surefire-reports/*.xml'
              failTaskOnFailedTests: true
          
          - task: SendEmail@0
            inputs:
              To: 'ayyappangunasekaran5@gmail.com'
              CC: 'ayyappangunasekaran5@gmail.com'
              From: 'ayyappangunasekaran5@gmail.com'
              Subject: 'Ran from AzureDevops task mail'
              Body: 'Test result bro'
              Attachment: '$(System.DefaultWorkingDirectory)/target/surefire-reports/*.xml'
              SmtpServer: 'smtp.zoho.in'
              SmtpPort: '465'
              SmtpUsername: 'ayyappansg1@zohomail.in'
              SmtpPassword: 'FArvYhxi2Emk'